### ISSUE TITLE
Regarding Av value 

### ISSUE THREAD

**Issue by sonithls** [jvines/astroARIADNE#38]
I have a question regarding the Av value used in the code while using the Bayestar and SFD model.

The multiplication factor used in code "2.742" is for the Landolt V filter in the SFD model, right?  [https://iopscience.iop.org/article/10.1088/0004-637X/737/2/103#apj398709t6](https://iopscience.iop.org/article/10.1088/0004-637X/737/2/103#apj398709t6). Don't you need to use `self.Av = 3.1 * ebv `  since later on you use ` ext = av_law(wav, Av, Rv)`  (where Rv is 3.1) to get extinction values for corresponding to different wavelengths ? Pardon me if something is wrong with my understanding. 

https://github.com/jvines/astroARIADNE/blob/1612546eea8b518e16e390f5836bcbd9e9c81a3b/astroARIADNE/star.py#L259-L282

**Comment by jvines** [comment]
Hi

So the [paper you linked](https://iopscience.iop.org/article/10.1088/0004-637X/737/2/103#apj398709t6) shows the table with $A_\text{b}/E(B-V)$ values in different bandpasses `b` for different Rvs, so $A_\text{v}/E(B-V) = 2.742 -> A_\text{v} = E(B-V) \cdot 2.742$ for $R_\text{v} = 3.1$. Since the dustmaps give the $E(B-V)$ value, which in the code is ebv, we multiply that by 2.742 to get the total extinction in V in `self.Av`

The actual reddening law comes from the [extinction package](https://extinction.readthedocs.io/en/latest/index.html) in which the documentation states the required parameters for computing the reddening are the Av, explicitly the "Total V-band extinction in magnitudes." and the Rv which is set to 3.1.

Does that answer your question?

**Comment by sonithls** [comment]
Yes. this answers my question; thank you. I was confused with the relation used in the IRAS portal [https://irsa.ipac.caltech.edu/applications/DUST/](https://irsa.ipac.caltech.edu/applications/DUST/)
E(B-V)_S & F =  0.86 x E(B-V)_SFD
Av / E(B-V) = 3.1
I realise both will give the same Av value for S & F.
