### ISSUE TITLE
Regarding BT-Models

### ISSUE THREAD

**Issue by sonithls** [jvines/astroARIADNE#39]
I am not able to download the BT-Models from the link provided ([http://osubdd.ens-lyon.fr/phoenix/](http://osubdd.ens-lyon.fr/phoenix/)).
They are providing the files in text format ([https://phoenix.ens-lyon.fr/Grids/BT-Settl/AGSS2009/SPECTRA/](https://phoenix.ens-lyon.fr/Grids/BT-Settl/AGSS2009/SPECTRA/)) which is not compatible with [astroARIADNE](https://github.com/jvines/astroARIADNE).
I have found fits files available from here. 'https://lydu.ens-lyon.fr/phoenix/phoenix.cgi?n=btsettl&c=o&a=htab' but it is also not compatible. 

Can you provide any other source where I can obtain the BT-Settl models?

**Comment by jvines** [comment]
The source provided in the readme is, indeed, correct.

If you wanted to download, for example, the BT-Settl models, you'd need to go to the [phoenix site](http://osubdd.ens-lyon.fr/phoenix/) and select BT-Settl in the BT models dropdown list.

This will land you on [this site](https://osubdd.ens-lyon.fr/phoenix/phoenix.cgi?n=btsettl&c=o&z=e[f!]&a=htab) where you can query for specific spectra or spectra for ranges of values. I'd recommend you select the values we highlight in [the paper](https://ui.adsabs.harvard.edu/abs/2022MNRAS.513.2719V/abstract). There are instructions in the query form on how to put constraints on the parameters.

Once you're happy with your selection, you can press the submit button at it will load an HTML table with all the spectra within your selected range, and if you scroll to the bottom you'll find a link  that says "Get the wget commands to download these spectra" where you can download a text file with the wget commands to download the spectra which in turn you can run from a terminal or otherwise.

Hope this helps you in downloading the spectra.

**Comment by sonithls** [comment]
After following the procedure you mentioned, I can download those spectra (.fits files). But that only contains the fits header (with zero number of raws).  Somehow the data is missing from the file. I can get a text file in table format which contains a table. But I can't give them as input for  [astroARIADNE](https://github.com/jvines/astroARIADNE). Also when I tried to display the spectra using [the site](https://osubdd.ens-lyon.fr/phoenix/phoenix.cgi?n=btsettl&c=o&z=e%5Bf!%5D&a=htab) you mentioned, I am getting only empty plots. I find there is some issue with the fits file generated from the site. 

Is there something I am missing? 
Thank you for your help

**Comment by jvines** [comment]
You're right. When asking for the plots I also get an empty figure, which is strange... That website is where I got them from in the first place, maybe there's a bug in their end?

[Try out downloading them from VOSA instead](http://svo2.cab.inta-csic.es/theory/newov2/), let me know if that works for you, but be careful to have them organized the same way as in the README.

**Comment by sonithls** [comment]
I have tried this early. But I was getting the following error.

PyAValError: 
---------------------
A PyA error occurred:
---------------------
Type of error: PyA Value Error
What happened?
    The wavelength axis is not equidistant, which is required.
Where did it happen?
    instrBroadGaussFast
What are possible solutions?
  - Define equidistant wavelength axis
  - Set 'equid' to True

**Comment by jvines** [comment]
I see what's going on. For some reason, the spectra disappeared from the archive site I mentioned and the one in VOSA has a different wavelength grid for whatever reason.

I'd wait a couple of days to see if the spectra return to the site, otherwise, I'll need to check in more detail the one from VOSA and see how much it differs and if it can be fixed somehow. Sadly right now I cannot do that, however, so it would have to wait a bit.

**Comment by sonithls** [comment]
On the above said [website](https://lydu.ens-lyon.fr/phoenix/phoenix.cgi?n=btsettl&c=o&a=htab), there is an option to download native files. But I can not identify which columns are used for flux. If you can tell me which column is used for wavelength and flux, I can reproduce the fits files. This can solve my issue.

**Comment by jvines** [comment]
Given that the BT models are still missing, what I can offer you is that you instead download either the Kurucz or Castelli & Kurucz models and force ARIADNE to plot those instead. Those models are just for plotting anyway.

If that's OK with you I can tell you how to do that.

**Comment by sonithls** [comment]
I figured it out. Thank you. I have one more question.
If an error in magnitudes is not available on some filter, What is the value you use?

**Comment by jvines** [comment]
You can find that information in the paper :)
